image:
  repository: maxwo/snmp-notifier
  pullPolicy: IfNotPresent
  tag: "main"

nodeSelector:
  node-group: infra

replicaCount: 1

snmpNotifier:
  extraArgs:
    - --log.level=debug
    - --snmp.retries=10
    - --snmp.destination=snmp-server:162
  snmpTemplates: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 9464

resources: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

tolerations: []
affinity: {}
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: snmp-notifier.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceMonitor:
  enabled: false
  namespace: monitoring
  interval: 30s
  telemetryPath: /metrics
  labels: {}
  timeout: 10s
  targetLabels: []
  metricRelabelings: []
  relabelings: []