{
 "title": "API",
 "tags": [ "API" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "app", "query": "api" },
   { "name": "hikaricp", "query": "api-db-pool" },
   { "name": "podInfo", "query": "node:{{node}} - pod:{{pod}}" },
   { "name": "timeRate", "label": "Time Rate", "query": "1m,5m,15m" }
  ]
 },
 "panels": [
  { "title": "API HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{app=\"$app\", uri=~\".*gsmsession.*\"}[$timeRate]))",
     "legendFormat": "/v1/gsmsession"
    }
   ]
  },
  {
   "title": "Requests Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n    rate(http_server_requests_seconds_sum{status=\"200\", uri=~\".*gsmsession.*\"}) \n    / \n    rate(http_server_requests_seconds_count{status=\"200\", uri=~\".*gsmsession.*\"})[$timeRate]\n)",
     "legendFormat": "/v1/gsmsession"
    }
   ]
  },
  {
   "title": "99% Requests Seconds / Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_latency_seconds_bucket[$timeRate])) by (host, le))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Error Rate / In General",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(http_server_requests_seconds_count{app=\"$app\", status!=\"200\", uri=~\".*gsmsession.*\"})\n    /\n    rate(http_server_requests_seconds_count{app=\"$app\", uri=~\".*gsmsession.*\"})\n    [$timeRate]\n)",
     "legendFormat": "/v1/gsmsession"
    }
   ]
  },
  { "title": "PCF HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Requests/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{app=\"$app\"}[$timeRate]))",
     "legendFormat": "/axis/services/ScfPccSoapServiceEndpointPort"
    }
   ]
  },
  {
   "title": "Requests Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(\n    rate(http_client_requests_seconds_sum{status=\"200\"}) / \n    rate(http_client_requests_seconds_count{status=\"200\"})[$timeRate]\n)",
     "legendFormat": "/axis/services/ScfPccSoapServiceEndpointPort"
    }
   ]
  },
  {
   "title": "99% Requests Seconds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_latency_seconds_bucket[$timeRate])) by (host, le))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "99% Requests Seconds / Per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_latency_seconds_bucket[$timeRate])) by (host, le))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Error Rate / In General",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(http_client_requests_seconds_count{app=\"$app\", status!=\"200\"})\n    /\n    rate(http_client_requests_seconds_count{app=\"$app\"})\n    [$timeRate]\n)",
     "legendFormat": "/axis/services/ScfPccSoapServiceEndpointPort"
    }
   ]
  },
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "In Use",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{app=\"$app\", pool=\"$hikaricp\"})"
    }
   ]
  },
  {
   "title": "Connections Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{app=\"$app\", pool=\"$hikaricp\"}",
     "legendFormat": "Active - node:{{node}} - pod:{{pod}}"
    },
    {
     "expr": "hikaricp_connections_idle{app=\"$app\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle - node:{{node}} - pod:{{pod}}"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{app=\"$app\",  pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{app=\"$app\", pool=\"$hikaricp\"}",
     "legendFormat": "$podInfo"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max{app=\"$app\", pool=\"$hikaricp\"})"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_min{app=\"$app\", pool=\"$hikaricp\"})"
    }
   ]
  },
  {
   "title": "Connections Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(hikaricp_connections_timeout_total{app=\"$app\", pool=\"$hikaricp\"}[$timeRate])",
     "legendFormat": "node:{{node}} - pod:{{pod}}"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{app=\"$app\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{app=\"$app\", pool=\"$hikaricp\"}",
     "legendFormat": "$podInfo"
    }
   ]
  },
  {
   "title": "Timeout",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hikaricp_connections_timeout_total{app=\"$app\", pool=\"$hikaricp\"}[5m]))"
    }
   ]
  },
  { "title": "Logback Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "CDR Generated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cdr_success_total{app=\"$app\"}[$timeRate])",
     "legendFormat": "$podInfo",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "INFO Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{app=\"$app\", level=\"info\"}[$timeRate])",
     "legendFormat": "$podInfo",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{app=\"$app\", level=\"error\"}[$timeRate])",
     "legendFormat": "$podInfo",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}