---
apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Chart.Name}}
spec:
  selector:
    app: {{.Chart.Name}}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.pod.port}}
  type: {{.Values.service.type}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Chart.Name}}
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
      annotations:
        {{- with .Values.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      nodeSelector:
      {{toYaml .Values.pod.nodeSelector | indent 8}}
      containers:
        - name: {{.Chart.Name}}
          image: {{.Values.pod.image}}
          ports:
            - containerPort: {{.Values.pod.port}}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{.Values.env}}
            - name: POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: log
              mountPath: /var/log
      volumes:
      - name: log
        hostPath:
          path: /var/log
