---
namespace: app
env: localk8s

service:
  port: 80
  type: ClusterIP

pod:
  image: local/api:24-11-18-16
  port: 8080
  annotations:  
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
  nodeSelector:
    node-group: app

deployment:
  replicas: 2